import { DocumentInfo, Finding, MissingDocument } from '../types';
import { riskThemes, matterTimeline } from '../data/mockData';

export function generateReportText(
  documentInfo: DocumentInfo,
  findings: Finding[],
  missingDocs: MissingDocument[]
): string {
  const divider = '='.repeat(76);
  const subDivider = '-'.repeat(76);
  const activeBrief = findings.filter((f) => f.inAdvocateBrief);

  return `${divider}
VIDHI — CITIZEN-FIRST LEGAL ASSISTANT
DOCUMENT RISK REVIEW & ADVOCATE CONSULTATION REPORT
${divider}

MATTER OVERVIEW
Document Name    : ${documentInfo.title}
Property Address : ${documentInfo.property}
Jurisdiction     : ${documentInfo.city}
Total Value      : ${documentInfo.totalConsideration}
Reviewed         : ${documentInfo.reviewedTimeAgo} · ${documentInfo.pageCount} Pages (${documentInfo.version})
Risk Verdict     : ${documentInfo.riskScore}/100 — ${documentInfo.riskVerdict.toUpperCase()}
Total Flags      : ${findings.length} Flagged Points (${documentInfo.highCount} HIGH, ${documentInfo.mediumCount} MEDIUM, ${documentInfo.lowCount} LOW)

LEGAL DISCLAIMER:
Vidhi explains documents and procedures in plain language. It is not a law
firm, does not provide legal advice, and concludes reviews with questions
to take to an advocate.
${divider}

EXECUTIVE SUMMARY (AI-GENERATED PLAIN-LANGUAGE BRIEF)
${subDivider}
HEADLINE:
Outright purchase of Flat 402, Kalyani Nagar for ₹86,00,000/-. Review and amendment of 3 key clauses strongly recommended prior to sub-registrar execution.

TRANSACTION SUMMARY:
• Target Asset     : Flat 402, 4th Floor, Gulmohar Enclave CHSL, Kalyani Nagar, Pune
• Transfer Scope   : 1,180 sq. ft. flat, covered stilt car park P-14 & undivided land share
• Financial Terms  : ₹17.20 Lakhs token paid; ₹68.80 Lakhs balance due on execution
• Mortgage Status  : Outstanding home loan registered with State Bank of India Commercial Branch

CRITICAL COMMITMENT WARNINGS:
1. Clause 4 (Page 7)  : Balance payment is unlinked from the seller's SBI mortgage release.
2. Clause 9 (Page 11) : Vacant keys handover deadline is waived for seller, while your payment deadline is strict.
3. Clause 16 (Page 15): Seller restricts title defect indemnity to 12 months (statutory period is 12 years).
${divider}

SECTION 1: RISK THEMES ANALYSIS
${subDivider}
${riskThemes
  .map(
    (theme) =>
      `• ${theme.label.padEnd(28)} : [${theme.severity.padEnd(6)}] (Risk Exposure: ${theme.percent}%)`
  )
  .join('\n')}

${divider}

SECTION 2: BRIEF FOR YOUR ADVOCATE (CONSULTATION QUESTIONS)
${subDivider}
Four questions, and why each one is being asked before sub-registrar registration:

${activeBrief
  .map((f, idx) => {
    const num = (idx + 1).toString().padStart(2, '0');
    return `[${num}] QUESTION:
    "${f.advocateQuestion}"
    
    LEGAL JUSTIFICATION (WHY ASK THIS):
    ${f.advocateWhy}
    
    SOURCE REFERENCE: Clause ${f.clauseNumber}, Page ${f.pageNumber} (${f.severity} RISK)`;
  })
  .join('\n\n')}

${divider}

SECTION 3: DETAILED FLAGGED FINDINGS & PLAIN-LANGUAGE EXPLANATIONS
${subDivider}
${findings
  .map((f, idx) => {
    return `FLAG #${idx + 1}: ${f.severity} RISK · CLAUSE ${f.clauseNumber}, PAGE ${f.pageNumber}
Theme: ${f.theme}

PLAIN-LANGUAGE SUMMARY:
${f.plainHeadline}

EXACT DEED TEXT:
"${f.sourceQuote}"

IN PLAIN LANGUAGE:
${f.plainLanguageExplanation}

PRACTICAL CONSEQUENCES IN REAL LIFE:
${f.practicalConsequences.map((c) => `  - ${c}`).join('\n')}

RECOMMENDED QUESTION FOR ADVOCATE:
"${f.advocateQuestion}"
----------------------------------------------------------------------------`;
  })
  .join('\n\n')}

${divider}

SECTION 4: MISSING DOCUMENTS & DUE DILIGENCE CHECKLIST
${subDivider}
${missingDocs
  .map(
    (doc) =>
      `[${doc.uploaded ? 'VERIFIED' : 'PENDING '}] ${doc.title} (${doc.importance.toUpperCase()})
  Purpose: ${doc.reason}`
  )
  .join('\n\n')}

${divider}

SECTION 5: MATTER TIMELINE & CRITICAL DEADLINES
${subDivider}
${matterTimeline
  .map(
    (ev) =>
      `• ${ev.date} [${ev.status}]
  ${ev.title}
  ${ev.description}${ev.location ? `\n  Location: ${ev.location}` : ''}`
  )
  .join('\n\n')}

${divider}
REPORT GENERATED BY VIDHI · FOR CITIZEN ADVOCATE CONSULTATION
CONFIDENTIAL · PREPARED FOR APPOINTMENT ON 14 & 19 SEPTEMBER 2026
${divider}
`;
}

export function exportReportAsText(
  documentInfo: DocumentInfo,
  findings: Finding[],
  missingDocs: MissingDocument[]
): void {
  const content = generateReportText(documentInfo, findings, missingDocs);
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  const fileName = `Vidhi-Report-${documentInfo.title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}.txt`;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportReportAsPdf(
  documentInfo: DocumentInfo,
  findings: Finding[],
  missingDocs: MissingDocument[]
): void {
  const activeBrief = findings.filter((f) => f.inAdvocateBrief);

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Vidhi Report — ${documentInfo.title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,400;0,600;1,400&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');
    
    @page {
      margin: 18mm 15mm;
      size: A4 portrait;
    }
    
    body {
      font-family: 'Plus Jakarta Sans', system-ui, -apple-system, sans-serif;
      color: #1C1C19;
      background: #FFFFFF;
      line-height: 1.5;
      font-size: 13px;
      margin: 0;
      padding: 24px;
    }
    
    .header {
      border-bottom: 2px solid #171714;
      padding-bottom: 16px;
      margin-bottom: 20px;
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
    }
    
    .brand {
      font-family: 'Newsreader', serif;
      font-size: 26px;
      font-weight: 700;
      letter-spacing: 1px;
      color: #171714;
    }
    
    .badge {
      display: inline-block;
      font-size: 10px;
      font-weight: 700;
      text-transform: uppercase;
      padding: 3px 7px;
      border-radius: 4px;
      letter-spacing: 0.5px;
    }
    
    .badge-high { background: #F5E3DE; color: #B44738; }
    .badge-medium { background: #F3ECD7; color: #B08427; }
    .badge-low { background: #E6EEE6; color: #58735C; }
    .badge-amber { background: #F2E6C9; color: #C38A2E; }
    
    .risk-score {
      font-size: 32px;
      font-weight: 800;
      color: #171714;
      line-height: 1;
    }
    
    .section-title {
      font-size: 14px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: #6F6D65;
      border-bottom: 1px solid #DDD9CE;
      padding-bottom: 6px;
      margin-top: 24px;
      margin-bottom: 12px;
    }
    
    .card {
      border: 1px solid #DDD9CE;
      border-radius: 6px;
      padding: 12px 14px;
      margin-bottom: 12px;
      background: #FCFBF7;
      page-break-inside: avoid;
    }
    
    .quote-box {
      font-family: 'Newsreader', Georgia, serif;
      font-style: italic;
      background: #F7F4EC;
      border-left: 3px solid #C38A2E;
      padding: 8px 12px;
      font-size: 12px;
      margin: 8px 0;
      line-height: 1.45;
    }
    
    .table {
      width: 100%;
      border-collapse: collapse;
      font-size: 12px;
      margin-bottom: 16px;
    }
    
    .table th, .table td {
      border: 1px solid #DDD9CE;
      padding: 8px 10px;
      text-align: left;
    }
    
    .table th {
      background: #F7F4EC;
      font-weight: 600;
      color: #171714;
    }
    
    .disclaimer {
      font-size: 11px;
      color: #6F6D65;
      background: #F7F4EC;
      border: 1px solid #DDD9CE;
      border-radius: 6px;
      padding: 10px 12px;
      margin-bottom: 20px;
      line-height: 1.4;
    }
    
    .footer {
      border-top: 1px solid #DDD9CE;
      padding-top: 12px;
      margin-top: 30px;
      font-size: 10px;
      color: #96938A;
      display: flex;
      justify-content: space-between;
    }

    @media print {
      body { padding: 0; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="brand">VIDHI</div>
      <div style="font-size: 16px; font-weight: 600; margin-top: 4px;">${documentInfo.title}</div>
      <div style="font-size: 12px; color: #6F6D65;">${documentInfo.property} · ${documentInfo.city}</div>
      <div style="font-size: 11px; color: #96938A; margin-top: 2px;">Value: ${documentInfo.totalConsideration} · ${documentInfo.pageCount} Pages (${documentInfo.version})</div>
    </div>
    <div style="text-align: right;">
      <div class="risk-score">${documentInfo.riskScore}<span style="font-size: 14px; font-weight: normal; color: #96938A;">/100</span></div>
      <div class="badge badge-high" style="margin-top: 4px;">${documentInfo.riskVerdict}</div>
      <div style="font-size: 11px; color: #6F6D65; margin-top: 4px;">7 Points Flagged (2 High, 3 Med, 2 Low)</div>
    </div>
  </div>

  <div class="disclaimer">
    <strong>Vidhi Legal Notice:</strong> Vidhi explains documents and procedures in plain language. It is not a law firm, does not provide legal advice, and concludes reviews with questions to take to an advocate.
  </div>

  <!-- SECTION: EXECUTIVE SUMMARY -->
  <div class="section-title">Executive Summary (AI-Generated Plain-Language Brief)</div>
  <div class="card" style="background: #FAF8F2; border-left: 3px solid #C38A2E;">
    <div style="font-weight: 700; font-size: 13px; color: #171714; margin-bottom: 6px;">
      Outright sale of Flat 402, Kalyani Nagar for ₹86 Lakhs — 3 key amendments recommended prior to registration.
    </div>
    <div style="font-size: 12px; color: #4A4843; line-height: 1.5; margin-bottom: 8px;">
      This draft deed covers an 1,180 sq. ft. flat with covered stilt parking P-14 in Gulmohar Enclave CHSL. An advance of ₹17.20 Lakhs has been remitted, leaving ₹68.80 Lakhs payable at registration. State Bank of India holds an active housing loan charge on the flat.
    </div>
    <div style="font-size: 11px; color: #8E4A3F; background: #FAF3F1; padding: 6px 10px; border-radius: 4px; border: 1px solid #EADBDA;">
      <strong>Action Required:</strong> Clause 4 unlinks balance payment from the bank mortgage release, Clause 9 waives vacant key handover time for the seller, and Clause 16 restricts title indemnity to 12 months. Review with advocate recommended.
    </div>
  </div>

  <!-- SECTION: ADVOCATE BRIEF -->
  <div class="section-title">1. Brief for Your Advocate (Key Consultation Questions)</div>
  <p style="font-size: 12px; color: #6F6D65; margin-top: 0;">Submit these specific questions to your advocate before executing the registered sale deed:</p>
  ${activeBrief
    .map(
      (f, idx) => `
    <div class="card" style="border-left: 3px solid #C38A2E;">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <span style="font-weight: 700; color: #C38A2E; font-size: 14px;">Question 0${idx + 1}</span>
        <span class="badge ${f.severity === 'HIGH' ? 'badge-high' : 'badge-medium'}">Clause ${f.clauseNumber}, Page ${f.pageNumber} (${f.severity})</span>
      </div>
      <div style="font-weight: 600; font-size: 13px; margin: 6px 0; color: #171714;">"${f.advocateQuestion}"</div>
      <div style="font-size: 12px; color: #6F6D65;"><strong style="color: #171714;">Why this is asked:</strong> ${f.advocateWhy}</div>
    </div>
  `
    )
    .join('')}

  <!-- SECTION: DETAILED FINDINGS -->
  <div class="section-title" style="page-break-before: always;">2. All Flagged Clauses & Plain Explanations</div>
  ${findings
    .map(
      (f, idx) => `
    <div class="card">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <span class="badge ${
          f.severity === 'HIGH' ? 'badge-high' : f.severity === 'MEDIUM' ? 'badge-medium' : 'badge-low'
        }">${f.severity} RISK · CLAUSE ${f.clauseNumber}, PAGE ${f.pageNumber}</span>
        <span style="font-size: 11px; color: #96938A;">${f.theme}</span>
      </div>
      <h3 style="margin: 6px 0 4px 0; font-size: 13px; font-weight: 600; color: #1C1C19;">${f.plainHeadline}</h3>
      <div class="quote-box">"${f.sourceQuote}"</div>
      <div style="font-size: 12px; margin-top: 6px; color: #1C1C19;"><strong>What it means:</strong> ${f.plainLanguageExplanation}</div>
      <div style="font-size: 12px; color: #6F6D65; margin-top: 4px;">
        <strong>Consequences:</strong>
        <ul style="margin: 4px 0 0 0; padding-left: 18px;">
          ${f.practicalConsequences.map((c) => `<li>${c}</li>`).join('')}
        </ul>
      </div>
    </div>
  `
    )
    .join('')}

  <!-- SECTION: MISSING DOCUMENTS -->
  <div class="section-title">3. Due Diligence & Missing Documents Checklist</div>
  <table class="table">
    <thead>
      <tr>
        <th style="width: 35%;">Required Document</th>
        <th style="width: 15%;">Importance</th>
        <th style="width: 50%;">Verification Purpose</th>
      </tr>
    </thead>
    <tbody>
      ${missingDocs
        .map(
          (d) => `
        <tr>
          <td><strong>${d.title}</strong></td>
          <td><span class="badge ${d.importance === 'Critical' ? 'badge-high' : 'badge-amber'}">${d.importance}</span></td>
          <td>${d.reason}</td>
        </tr>
      `
        )
        .join('')}
    </tbody>
  </table>

  <!-- SECTION: TIMELINE -->
  <div class="section-title">4. Key Deadlines</div>
  <table class="table">
    <thead>
      <tr>
        <th style="width: 25%;">Date</th>
        <th style="width: 30%;">Milestone</th>
        <th style="width: 45%;">Details</th>
      </tr>
    </thead>
    <tbody>
      ${matterTimeline
        .map(
          (t) => `
        <tr>
          <td><strong>${t.date}</strong></td>
          <td>${t.title}</td>
          <td>${t.description}</td>
        </tr>
      `
        )
        .join('')}
    </tbody>
  </table>

  <div class="footer">
    <div>VIDHI REPORT · MATTER: FLAT 402, KALYANI NAGAR, PUNE</div>
    <div>CONFIDENTIAL · PREPARED FOR ADVOCATE CONSULTATION</div>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 500);
    };
  </script>
</body>
</html>
`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.open();
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  } else {
    // If popup blocked, create an invisible iframe
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);
    iframe.contentDocument?.open();
    iframe.contentDocument?.write(htmlContent);
    iframe.contentDocument?.close();
    iframe.contentWindow?.focus();
    setTimeout(() => {
      iframe.contentWindow?.print();
      setTimeout(() => document.body.removeChild(iframe), 2000);
    }, 500);
  }
}
